package co.com.harrybooksweb.model;
// Generated 16/09/2017 02:12:55 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Libro generated by hbm2java
 */
@Entity
@Table(name="libro"
    ,catalog="harrybooksbd"
)
public class Libro  implements java.io.Serializable {


     private Integer idLibro;
     private String tituloLibro;
     private Double precioLibro;
     private String cantidadDisponible;
     private byte[] imagenLibro;

    public Libro() {
    }

	
    public Libro(Integer idLibro) {
        this.idLibro = idLibro;
    }
    public Libro(Integer idLibro, String tituloLibro, Double precioLibro, String cantidadDisponible, byte[] imagenLibro) {
       this.idLibro = idLibro;
       this.tituloLibro = tituloLibro;
       this.precioLibro = precioLibro;
       this.cantidadDisponible = cantidadDisponible;
       this.imagenLibro = imagenLibro;
    }
   
     @Id 

    
    @Column(name="id_libro", unique=true, nullable=false)
    public Integer getIdLibro() {
        return this.idLibro;
    }
    
    public void setIdLibro(Integer idLibro) {
        this.idLibro = idLibro;
    }

    
    @Column(name="titulo_libro", length=45)
    public String getTituloLibro() {
        return this.tituloLibro;
    }
    
    public void setTituloLibro(String tituloLibro) {
        this.tituloLibro = tituloLibro;
    }

    
    @Column(name="precio_libro", precision=22, scale=0)
    public Double getPrecioLibro() {
        return this.precioLibro;
    }
    
    public void setPrecioLibro(Double precioLibro) {
        this.precioLibro = precioLibro;
    }

    
    @Column(name="cantidad_disponible", length=45)
    public String getCantidadDisponible() {
        return this.cantidadDisponible;
    }
    
    public void setCantidadDisponible(String cantidadDisponible) {
        this.cantidadDisponible = cantidadDisponible;
    }

    
    @Column(name="imagen_libro")
    public byte[] getImagenLibro() {
        return this.imagenLibro;
    }
    
    public void setImagenLibro(byte[] imagenLibro) {
        this.imagenLibro = imagenLibro;
    }




}


