package co.com.harrybooksweb.model;
// Generated 16/09/2017 02:12:55 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="harrybooksbd"
)
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private String nombreUsuario;
     private Integer estadoUsuario;
     private Integer perfilUsuario;
     private String contrasenaUsuario;

    public Usuario() {
    }

	
    public Usuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Usuario(int idUsuario, String nombreUsuario, Integer estadoUsuario, Integer perfilUsuario, String contrasenaUsuario) {
       this.idUsuario = idUsuario;
       this.nombreUsuario = nombreUsuario;
       this.estadoUsuario = estadoUsuario;
       this.perfilUsuario = perfilUsuario;
       this.contrasenaUsuario = contrasenaUsuario;
    }
   
     @Id 

    
    @Column(name="id_usuario", unique=true, nullable=false)
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    
    @Column(name="nombre_usuario", length=45)
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }

    
    @Column(name="estado_usuario")
    public Integer getEstadoUsuario() {
        return this.estadoUsuario;
    }
    
    public void setEstadoUsuario(Integer estadoUsuario) {
        this.estadoUsuario = estadoUsuario;
    }

    
    @Column(name="perfil_usuario")
    public Integer getPerfilUsuario() {
        return this.perfilUsuario;
    }
    
    public void setPerfilUsuario(Integer perfilUsuario) {
        this.perfilUsuario = perfilUsuario;
    }

    
    @Column(name="contrasena_usuario", length=45)
    public String getContrasenaUsuario() {
        return this.contrasenaUsuario;
    }
    
    public void setContrasenaUsuario(String contrasenaUsuario) {
        this.contrasenaUsuario = contrasenaUsuario;
    }




}


